config/routes.rb
Rails.application.routes.draw do
  resources :drop_off_packages do
    collection do
      get 'receipt'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    # admins can perform any action on any objects
    can :manage, :all if user.role == "admin"
    # employees can only manage DropOffPackages they created
    can :manage, DropOffPackage, user_id: user.id if user.role == "employee"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drop_off_package.rb
class DropOffPackage < ApplicationRecord
  belongs_to :user
  validates :tracking_ref, presence: true,
    tracking_number: { message: "is not valid" },
    uniqueness: { message: "has already been dropped off"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
  :rememberable, :trackable, :validatable
  has_many :drop_off_packages
  ROLES = %i[admin employee]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drop_off_packages_controller.rb
class DropOffPackagesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_trackobjs, only: [:new, :create, :receipt]

  # GET /drop_off_packages
  # GET /drop_off_packages.json
  def index
    session.delete :tracknos
  end

  # GET /drop_off_packages/1
  # GET /drop_off_packages/1.json
  def show
  end

  # GET /drop_off_packages/new
  def new
    @drop_off_package = DropOffPackage.new
  end

  # GET /drop_off_packages/1/edit
  def edit
  end

  # POST /drop_off_packages
  # POST /drop_off_packages.json
  def create
    @drop_off_package = DropOffPackage.new(drop_off_package_params)
    @drop_off_package.user = current_user
    @drop_off_package.carrier = TrackingNumber.
      new(@drop_off_package.tracking_ref).carrier.to_s.upcase
    respond_to do |format|
      if params.key?(:receipt) && !drop_off_package_params[:tracking_ref].present?
        format.html { redirect_to receipt_drop_off_packages_path }
      elsif params.key?(:done) && !drop_off_package_params[:tracking_ref].present?
        format.html { redirect_to drop_off_packages_path, notice: 'Drop off packages successfully created.' }
      elsif @drop_off_package.save
        format.json { render :show, status: :created, location: @drop_off_package }
        if params[:more]
          # initialize an array stored in session if it doesn't already exist, append drop_off_package.id
          (session[:tracknos] ||= []) << @drop_off_package.id
          @more = true
          format.html { redirect_to new_drop_off_package_path }
        elsif params.key? :done
          session.delete :tracknos
          format.html { redirect_to receipt_drop_off_packages_path, notice: 'Drop off packages successfully created.' }
        elsif params.key? :receipt
          format.html { redirect_to receipt_drop_off_packages_path }
        end
      else
        format.html { render :new }
        format.json { render json: @drop_off_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drop_off_packages/1
  # PATCH/PUT /drop_off_packages/1.json
  def update
    respond_to do |format|
      if @drop_off_package.update(drop_off_package_params)
        format.html { redirect_to @drop_off_package, notice: 'Drop off package was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop_off_package }
      else
        format.html { render :edit }
        format.json { render json: @drop_off_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drop_off_packages/1
  # DELETE /drop_off_packages/1.json
  def destroy
    id = @drop_off_package.id
    @drop_off_package.destroy
    respond_to do |format|
      if params[:more]
        session[:tracknos].delete(id)
        format.html { redirect_to new_drop_off_package_path }
      else
        format.html { redirect_to drop_off_packages_url, notice: 'Drop off package was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  # GET /receipt
  def receipt
    session.delete :tracknos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop_off_package
      @drop_off_package = DropOffPackage.find(params[:id])
    end
    # before_action to set @trackobjs
    def set_trackobjs
      @trackobjs = {}
      if session.key? :tracknos
        session[:tracknos].each do |v|
          @trackobjs[v] = DropOffPackage.find(v)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_off_package_params
      params.require(:drop_off_package).permit(:tracking_ref)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drop_off_packages_helper.rb
module DropOffPackagesHelper
end

app/views/drop_off_packages/_form.html.erb
<%= form_with(model: drop_off_package, local: true) do |form| %>
  <% if drop_off_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drop_off_package.errors.count, "error") %> prohibited this drop_off_package from being saved:</h2>

      <ul>
      <% drop_off_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tracking_ref %>
    <%= form.text_field :tracking_ref, id: :drop_off_package_tracking_ref, autofocus: @drop_off_package.new_record?, autocomplete: false, size: 50 %>
  </div>

  <div class="actions">
  <% if drop_off_package.persisted? %> <%# if persisted, we are doing an update %>
    <%= form.submit %>
  <% else %>
    <%= form.submit("More", name: "more", style: "display: none;") %>
    <%= form.submit("Receipt", name: "receipt") %>
    <%= form.submit("Done", name: "done") %>
  <% end %>
  </div>
<% end %>

app/views/drop_off_packages/edit.html.erb
<h1>Editing Drop Off Package</h1>

<%= render 'form', drop_off_package: @drop_off_package %>

<%= link_to 'Show', @drop_off_package %> |
<%= link_to 'Back', drop_off_packages_path %>

app/views/drop_off_packages/index.html.erb
<h1>Drop Off Packages</h1>

<table>
  <thead>
    <tr>
      <% if current_user.role == "admin" %>
      <th>User</th>
      <% end %>
      <th>Tracking ref</th>
      <% if current_user.role == "admin" %>
      <th colspan="3"></th>
      <% else %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @drop_off_packages.each do |drop_off_package| %>
      <tr>
        <% if current_user.role == "admin" %>
        <td><%= drop_off_package.user.email %></td>
        <% end %>
        <td><%= drop_off_package.tracking_ref %></td>
        <td><%= link_to 'Show', drop_off_package %></td>
        <td><%= link_to 'Edit', edit_drop_off_package_path(drop_off_package) %></td>
        <td><%= link_to 'Destroy', drop_off_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drop Off Package', new_drop_off_package_path %>

app/views/drop_off_packages/new.html.erb
<h1>New Drop Off Package</h1>

<%= render 'form', drop_off_package: @drop_off_package %>

<table>
  <thead>
    <tr>
      <th>Carrier</th>
      <th>Tracking ref</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% if defined? @trackobjs %>
  <tbody>
  <% @trackobjs.each do |key, dropped_off_package| %>
      <tr>
        <td><%= dropped_off_package.carrier %></td>
        <td><%= dropped_off_package.tracking_ref %></td>
        <td><%= link_to 'Delete', drop_off_package_path(dropped_off_package, more: true), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

<%= link_to 'Back', drop_off_packages_path %>

app/views/drop_off_packages/receipt.html.erb
<table>
  <thead>
    <tr>
      <th>Carrier</th>
      <th>Tracking ref</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @trackobjs.each do |key, dropped_off_package| %>
      <tr>
        <td><%= dropped_off_package.carrier %></td>
        <td><%= dropped_off_package.tracking_ref %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Drop Off Package', new_drop_off_package_path %>
<%= link_to 'Index', drop_off_packages_path %>

app/views/drop_off_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tracking ref:</strong>
  <%= @drop_off_package.tracking_ref %>
</p>

<p>
  <strong>User:</strong>
  <%= @drop_off_package.user %>
</p>

<%= link_to 'Edit', edit_drop_off_package_path(@drop_off_package) %> |
<%= link_to 'Back', drop_off_packages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShipIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div style="position: relative; top: 0px; right: 15px; text-align: right;">
      <% if user_signed_in? %>
        <p><%= link_to current_user.email, edit_user_registration_path %> | <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></p>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>